# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180817_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='age',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tax',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
