# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slab',
        ),
    ]
