# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tax',
            field=models.CharField(max_length=10),
        ),
    ]
