# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180817_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='age',
            field=models.CharField(default='25', max_length=5),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(default='2000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tax',
            field=models.CharField(default='20000', max_length=10),
        ),
    ]
