# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180817_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='tax',
            field=models.CharField(max_length=100),
        ),
    ]
