# Generated by Django 2.1 on 2018-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
